# Check out https://docs.codemagic.io/getting-started/yaml/ for more information
# Please review and update values in curly braces

workflows:
    ios-flutter:
        name: Jitenge iOS 
        environment:
            vars:
                FLUTTER_MODULE_DIR: "{{ ADD YOUR PATH HERE }}"
                HOST_IOS_APP_DIR: "{{ ADD YOUR PATH HERE }}"
                XCODE_PROJECT: "{{ ADD WORKSPACE NAME HERE }}"
                XCODE_SCHEME: "{{ ADD SCHEME NAME HERE }}"
            xcode: latest
            cocoapods: default
            flutter: stable
        scripts:
            - |
                # build Flutter module
                cd $FLUTTER_MODULE_DIR
                flutter packages get
                flutter build ios --debug --no-codesign
           
        artifacts:
            - build/**/outputs/**/*.aab
            - build/ios/ipa/*.ipa
        publishing:
          email:
            recipients:
              - kenmusembi21@gmail.com
            notify:
              success: true     # To not receive a notification when a build succeeds
              failure: true     # To not receive a notification when a build fails