# Check out https://docs.codemagic.io/getting-started/yaml/ for more information
# Please review and update values in curly braces

workflows:
    ios-flutter:
        name: iOS App with Flutter Module
        environment:
            vars:
                FLUTTER_MODULE_DIR: "{{ ADD YOUR PATH HERE }}"
                HOST_IOS_APP_DIR: "{{ ADD YOUR PATH HERE }}"
                XCODE_PROJECT: "{{ ADD WORKSPACE NAME HERE }}"
                XCODE_SCHEME: "{{ ADD SCHEME NAME HERE }}"
            xcode: edge
            cocoapods: default
            flutter: stable
        scripts:
            - |
                # build Flutter module
                cd $FLUTTER_MODULE_DIR
                flutter packages get
                flutter build ios --debug --no-codesign
           
        artifacts:
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM