# Check out https://docs.codemagic.io/getting-started/yaml/ for more information
# Please review and update values in curly braces

workflows:
    ios-flutter:
        name: Jitenge iOS 
        environment:
            vars:
               # FLUTTER_MODULE_DIR: "{{ ADD YOUR PATH HERE }}"
               # HOST_IOS_APP_DIR: "{{ ADD YOUR PATH HERE }}"
                XCODE_PROJECT: "{{ RUNNER }}"
                XCODE_SCHEME: "{{ RUNNER }}"
            xcode: edge
            cocoapods: default
            flutter: stable
        scripts:
            - |
                # build Flutter module
                
                flutter build ios 
            - |
                # build iOS project
                
               
                xcode-project use-profiles
                xcode-project build-ipa --workspace "ios/Runner.xcworkspace" --scheme "Runner" 
           
        artifacts:
            - build/ios/ipa/*.ipa
            - build/**/outputs/**/*.aab
            - build/**/outputs/**/mapping.txt
            - flutter_drive.log
        publishing:
          email:
            recipients:
              - kenmusembi21@gmail.com
            notify:
              success: true     # To not receive a notification when a build succeeds
              failure: true     # To not receive a notification when a build fails